#!/bin/sh
# Unmount TrueCrypt volumes and kill blocking applications if necessary
TRUECRYPT="`command -v veracrypt || echo truecrypt` -t"
grace_period="${1:-10}"


truecrypt_umount_all() {
	$TRUECRYPT -l 2>&- | cut -d ' ' -f 3 | \
		xargs -r -d '\n' -- umount -i -- && \
	$TRUECRYPT -d "$@"
}


truecrypt_umount_all || \
{
	test "`id -u`" -eq 0 && \
	$TRUECRYPT -l | cut -d ' ' -f 4 | \
		xargs -r -d '\n' -n 1 -- readlink -f -- | \
		xargs -r -d '\n' -- fuser -M -m 2>&- | \
		xargs -r -- waitproc -qdtki "$grace_period" && \
	truecrypt_umount_all --force || \
	{
		r=$?
		exec >&2
		echo 'Something blocked (forcefully) unmounting one or more TrueCrypt partitions even after killing all processes using them. Those are left:'
		$TRUECRYPT -l
		exit $r
	}
}
