#!/bin/sh
# Unmount TrueCrypt volumes and kill blocking applications if necessary

TRUECRYPT='truecrypt --text --non-interactive'
grace_period="${1:-10}"

if ! $TRUECRYPT --dismount; then
	test "`id -u`" -eq 0 && \
	$TRUECRYPT --list | cut -d' ' -f4 | \
		xargs -r -d'\n' -n1 -- readlink -f -- | \
		xargs -r -d'\n' -- fuser -Mm 2>&- | \
		xargs -r -- waitproc -qdtki "$grace_period" && \
	$TRUECRYPT --dismount --force
	r=$?
	if [ $r != 0 ]; then
		echo 'Something blocked (forcefully) unmounting one or more TrueCrypt partitions even after killing all processes using them. Those are left:' >&2
		$TRUECRYPT --list >&2
		exit $r
	fi
fi
